// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.6
// source: load-balancer/pb/join.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_load_balancer_pb_join_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_load_balancer_pb_join_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_load_balancer_pb_join_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_load_balancer_pb_join_proto protoreflect.FileDescriptor

var file_load_balancer_pb_join_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6c, 0x6f, 0x61, 0x64, 0x2d, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2f,
	0x70, 0x62, 0x2f, 0x6a, 0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x1d, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70,
	0x42, 0x12, 0x5a, 0x10, 0x6c, 0x6f, 0x61, 0x64, 0x2d, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_load_balancer_pb_join_proto_rawDescOnce sync.Once
	file_load_balancer_pb_join_proto_rawDescData = file_load_balancer_pb_join_proto_rawDesc
)

func file_load_balancer_pb_join_proto_rawDescGZIP() []byte {
	file_load_balancer_pb_join_proto_rawDescOnce.Do(func() {
		file_load_balancer_pb_join_proto_rawDescData = protoimpl.X.CompressGZIP(file_load_balancer_pb_join_proto_rawDescData)
	})
	return file_load_balancer_pb_join_proto_rawDescData
}

var file_load_balancer_pb_join_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_load_balancer_pb_join_proto_goTypes = []interface{}{
	(*JoinRequest)(nil), // 0: pb.JoinRequest
}
var file_load_balancer_pb_join_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_load_balancer_pb_join_proto_init() }
func file_load_balancer_pb_join_proto_init() {
	if File_load_balancer_pb_join_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_load_balancer_pb_join_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_load_balancer_pb_join_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_load_balancer_pb_join_proto_goTypes,
		DependencyIndexes: file_load_balancer_pb_join_proto_depIdxs,
		MessageInfos:      file_load_balancer_pb_join_proto_msgTypes,
	}.Build()
	File_load_balancer_pb_join_proto = out.File
	file_load_balancer_pb_join_proto_rawDesc = nil
	file_load_balancer_pb_join_proto_goTypes = nil
	file_load_balancer_pb_join_proto_depIdxs = nil
}
